export const SET_CURRENT_DATE = 'SET_CURRENT_DATE';
export const SET_WEATHER_LOCATION = 'SEARCHED_LOCATION';
export const WEATHER_LOCATION_LOADED = 'WEATHER_LOCATION_LOADED';

export const SET_UNITS = 'SET_UNITS';

export const SET_CURRENT_WEATHER = 'SET_CURRENT_WEATHER';
export const SET_FORECAST_CURRENT_HOUR = 'SET_FORECAST_CURRENT_HOUR'; 
export const SET_CURRENT_WEATHER_ICON = 'SET_CURRENT_WEATHER_ICON';
export const SET_FORECAST_WEATHER = 'SET_FORECAST_WEATHER';
export const SET_FORECAST_TODAY = 'SET_FORECAST_TODAY';

export const UPDATE_RECENT_SEARCHES = 'UPDATE_RECENT_SEARCHES';
export const CLEAR_RECENT_SEARCHES = 'CLEAR_RECENT_SEARCHES';
